# docker-compose.yml
services:
  web:
    container_name: fastapi_app
    build: .  
    command: ["/bin/sh", "-c", "/app/run_init_scripts.sh && uvicorn backend.app:app --host 0.0.0.0 --port 8000"]
    networks:
      - internal_network
    restart: on-failure
    ports:
      - "8000:8000"  # Expose port 8000 for FastAPI

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d/
    networks:
      - internal_network
    restart: on-failure

volumes:
  postgres_data:

networks:
  internal_network:
    driver: bridge
