#docker-compose.yml
services:
  web:
    build: .
    container_name: fastapi_app
    environment:
      SECRET_KEY: ${JWT_SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
    command: ["uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "8000"]
    deploy:
      replicas: 3  # 3 replicas of the FastAPI app
    networks:
      - internal_network
    restart: on-failure

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d/
    networks:
      - internal_network
    restart: on-failure

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./selfsigned.crt:/etc/nginx/ssl/selfsigned.crt
      - ./selfsigned.key:/etc/nginx/ssl/selfsigned.key
    ports:
      - "80:80"
      - "443:443"  # Expose HTTPS port
    depends_on:
      - web
    networks:
      - internal_network
    restart: on-failure

volumes:
  postgres_data:

networks:
  internal_network:
    driver: bridge
