services:
  web:
    build: .
    command: ["uvicorn", "backend.app:app", "--host", "0.0.0.0"]
    networks:
      - app-network
    profiles:
      - web
    restart: on-failure

networks:
  app-network:
    driver: bridge
