#docker-compose.web.yml
services:
  web:
    build: .
    command: ["uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "443", "--ssl-keyfile", "/app/selfsigned.key", "--ssl-certfile", "/app/selfsigned.crt"]
    networks:
      - app-network
    profiles:
      - web
    restart: on-failure
    ports:
      - "443:443"  # Expose HTTPS port 443

networks:
  app-network:
    driver: bridge
